# Generated by Django 3.1.1 on 2020-09-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='updated_on',
        ),
    ]
